// This file is generated by goaoop, DO NOT EDIT IT.
// see (github.com/chenjie4255/goaop) 
package example
import (
	"github.com/chenjie4255/goaop"
	
ppp "github.com/chenjie4255/goaop/example/param"
param2 "github.com/chenjie4255/goaop/example/param2"
)

type aopUserDB struct {
	UserDB
	builder goaop.PointcutBuilder
}

func NewUserDBAOP(o UserDB, builder goaop.PointcutBuilder) UserDB {
	return &aopUserDB{o, builder}
}


func (a *aopUserDB) GetUserCount() (int, error) {
	pointcut := a.builder.Build("GetUserCount")
	if pointcut == nil {
		return a.UserDB.GetUserCount()
	} else {
		pointcut.OnEntry()
		 r0,err := a.UserDB.GetUserCount()
		pointcut.OnReturn(err)
		return r0,err 
	}
}

func (a *aopUserDB) SetUserScore(userID string, score ppp.Score) {
	pointcut := a.builder.Build("SetUserScore")
	if pointcut == nil {
		a.UserDB.SetUserScore(userID ,score)
	} else {
		pointcut.OnEntry()
		a.UserDB.SetUserScore(userID ,score)
		pointcut.OnReturn(nil)
		
	}
}

func (a *aopUserDB) SetUserScores(userID string, scores []ppp.Score) error {
	pointcut := a.builder.Build("SetUserScores")
	if pointcut == nil {
		return a.UserDB.SetUserScores(userID ,scores)
	} else {
		pointcut.OnEntry()
		 err := a.UserDB.SetUserScores(userID ,scores)
		pointcut.OnReturn(err)
		return err 
	}
}

func (a *aopUserDB) RemoveUser(userIDs ...string) error {
	pointcut := a.builder.Build("RemoveUser")
	if pointcut == nil {
		return a.UserDB.RemoveUser(userIDs...)
	} else {
		pointcut.OnEntry()
		 err := a.UserDB.RemoveUser(userIDs...)
		pointcut.OnReturn(err)
		return err 
	}
}

func (a *aopUserDB) UpdateUserBatch(userIDs []string, scores []ppp.Score) (int, int) {
	pointcut := a.builder.Build("UpdateUserBatch")
	if pointcut == nil {
		return a.UserDB.UpdateUserBatch(userIDs ,scores)
	} else {
		pointcut.OnEntry()
		 r0,r1 := a.UserDB.UpdateUserBatch(userIDs ,scores)
		
		pointcut.OnReturn(nil)
		
		return r0,r1 
	}
}

func (a *aopUserDB) UpdateParam(userID string, p2 param2.Param2) error {
	pointcut := a.builder.Build("UpdateParam")
	if pointcut == nil {
		return a.UserDB.UpdateParam(userID ,p2)
	} else {
		pointcut.OnEntry()
		 err := a.UserDB.UpdateParam(userID ,p2)
		pointcut.OnReturn(err)
		return err 
	}
}


